2025-04-28 23:12:37,967 - INFO - Conexión exitosa a MySQL con SQLAlchemy
2025-04-28 23:12:40,708 - ERROR - Error al cargar datos: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'None' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-04-28 23:12:40,708 - ERROR - Error en el entrenamiento: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'None' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-04-28 23:13:30,388 - INFO - Conexión exitosa a MySQL con SQLAlchemy
2025-04-28 23:13:32,578 - INFO - Cargados 25000 registros simulados
2025-04-28 23:13:32,665 - INFO - Preprocesamiento completado: 19 características
2025-04-28 23:13:32,680 - INFO - Entrenamiento: 20000 registros, Validación: 5000 registros
2025-04-28 23:13:32,949 - INFO - Modelo compilado con métrica de accuracy personalizada
2025-04-28 23:15:09,377 - WARNING - You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. 
2025-04-28 23:15:09,499 - INFO - Modelo y preprocesadores guardados
2025-04-28 23:15:09,502 - INFO - Entrenamiento completado
